### ISSUE TITLE
Rewrite to-do

### ISSUE THREAD

**Issue by ThePjpollie** [AlphaConsole/AlphaConsoleBot#209]
Making a clear list so I know what things I still have to implement and what I have done.
I'll keep this list updated whenever new features are done.

If I'm missing any features be sure to let me know:

- [x] Main file & configuration setup
- [x] Connection with MySQL database made
- [x] Custom Commands
- [x] Swear words filter
- [x] Links filter
- [x] Invite guard filter
- [x] Auto responds
- [x] Permit feature
- [x] Ping Pong
- [x] Help command
- [x] Role & roleinfo command
- [x] Serverinfo command
- [x] Listroles command
- [x] Purge Command
- [x] Nick command
- [x] Suggestions & Showcase checks, delays & reactions
- [x] Functionality for reporting ingame players
- [x] Partners feature
- [x] Mute, unmute, kick & ban
- [x] Warn with the cases commands
- [x] Pinned messages for suggestions & showcase
- [x] Logging of every server activity (Users joining, leaving, renaming, role changes etc...)
- [x] Status functionality
- [x] Spam filter
- [x] Lockdown, unlock commands
- [x] Update functionality
- [x] Blacklist commands
- [x] Betaids feature for instant beta signups
- [x] Titles
- [x] Get title
